include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false
    # Make constructors the first thing in every class
    sort_constructors_first: true
    # Singel quotes
    prefer_single_quotes: true
    # Good packages document everything
    public_member_api_docs: false
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true
    # Back to the 80s
    lines_longer_than_80_chars: true
    # cancel stream subscription
    cancel_subscriptions: true
    # assignment
    invalid_assignment: true

    